---
title: "Graphics with ggplot2"
author: "Connor!"
date: "10/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Learning ggplot2

We're learning ggplot2

```{r}

# install packages

# install.packages("tidyverse")
## tidyverse is a "package of packages" and contains many of the packages we will use in the workshop, including ggplot2

library(tidyverse)

#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

Start with the California ('ca') dataset

```{r}
head(ca)
View(ca)
```

plot visitation to all CA NAtional Parks over time

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y= visitors))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y= visitors, color = park_name))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y= visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
  theme_bw() + # this changed to the black&white theme
  theme(legend.title = element_blank()) # this removed the legend title
```

```{r}
head(se)
View(se)
ggplot(data = se) +
  geom_point(aes(x= year, y= visitors, color = park_name))
  
```

```{r}
ggplot(data = se) +
  geom_point(aes(x= year, y= visitors, color = state)) +
  labs(x = "When", y = "How Many", title = "                                          Parks Alive!!!") +
  theme(axis.text.x = element_text(angle = 45, size = 14))

```

# Faceting plots

```{r}
ggplot(data =se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  facet_wrap(~ state, scales = "free")
```

# geoms

```{r}
ggplot(data = se) +
  geom_jitter(aes(x = park_name, y = visitors, color = park_name), alpha = 0.4, width = 0.1) +
  coord_flip()
```

```{r}
ggplot(se) +
  geom_line(aes(x = year, y = visitors, color = park_name)) +
  theme_bw()

```

# Multiple geoms  on one plot

```{r}
ggplot(data = acadia) +
  geom_point(aes(x = year, y = visitors)) +
  geom_line(aes(x = year, y = visitors)) +
  geom_smooth(aes(x = year, y = visitors))

```

```{r}
ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth()

```

# Bar Charts

```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")

```

# save a ggplot

```{r}
myplot <- ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")

myplot

ggsave(filename = "myplot.png", myplot)

```

