---
title: "Data Wrangling"
output: html_document
---

```{r}
library(tidyverse) # install.packages("tidyverse")

```

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

# inspect the data
gapminder # looks at all the data
head(gapminder) # gives the first 6 by default
tail(gapminder) # last observations, default is 6

head(gapminder, 3)
tail(gapminder, 10)

# summary statisics

str(gapminder)
summary(gapminder)

install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) # column names
dim(gapminder) # dimensions
ncol(gapminder) # number of columns
nrow(gapminder) # number of rows

# reverse-engineer dim
c(nrow(gapminder), ncol(gapminder))

```

## Dplyr!

```{r}
# filter by rows
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Rwanda"))
filter(gapminder, country == "Mexico", year == 2002)

#find mean life expectancy of Sweden
sweden <-  filter(gapminder, country == "Sweden")
mean(sweden$lifeExp)

```

```{r}
# select by columns
select(gapminder, year, lifeExp) # select only these columns
select(gapminder, -continent, -lifeExp) # will exclude these columns

# use select and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

```

Give 'Em the Pipe!!!!

```{r}
# this:
gapminder %>% head(3)
# is equivalent to:
head(gapminder, 3)

# let's improve with the Pipe!
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

gap_cambodia <- gapminder %>% filter(country == "Cambodia")
gap_cambodia2 <- gap_cambodia %>% select(-continent, -lifeExp)

gap_cambodia <- gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)

```

```{r}
# mutate adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder))

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

## Challenge:
#find the maximum gdpPercap of Egpyt and Vietnam. Create a new column

gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop *gdpPercap,
         max_gdp = max(gdp))

```

